# Generated by Django 3.2.16 on 2023-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='sort',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
