# Generated by Django 4.1.5 on 2023-01-17 20:15

from django.db import migrations

def reorder(apps, schema_editor):
    MyModel = apps.get_model('places', 'PlaceImage')
    for order, item in enumerate(MyModel.objects.all(), 1):
        item.my_order = order
        item.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20230115_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order']},
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
