# Generated by Django 4.1.5 on 2023-01-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_title_alter_placeimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='coordinate_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='coordinate_lng',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
